In [4]:
import cv2
# import numpy as np
import os
import pandas as pd

"""
NAO FUNCIONA SE AS IMAGENS ESTIVER NO DRIVE, TEM QUE ESTAR NO LOCAL HOST

"""

def calculate_dark_percentage(thresholded_img):
    if thresholded_img is None:
        return 0  # ou outro valor padrão, dependendo do seu caso
    total_pixels = thresholded_img.size
    black_pixels = cv2.countNonZero(thresholded_img)
    dark_percentage = (black_pixels / total_pixels) * 100
    return dark_percentage

def apply_threshold_to_images(input_folder, output_folder, output_file, threshold_value,cut_off_percentage):
    global df_output,root
    # Verifica se a pasta de saída para as imagens existe, senão a cria
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    # Abre o arquivo de saída para escrever as classificações
    with open(output_file, 'w') as file:
        # Percorre todas as imagens na pasta de entrada
        for filename in os.listdir(input_folder):
            # Verifica se o arquivo é uma imagem
            if filename.endswith(('.jpg', '.jpeg', '.png', '.bmp', '.gif')):
                # Lê a imagem
                img_path = os.path.join(input_folder, filename)
                img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
                
#                 # Identifica imagens com brilho "estourado"
#                 mean = np.mean(img)
#                 std_deviation = np.std(img)
#                 threshold_std = mean * threshold_std_mean
#                 print_std = std_deviation/mean
                
                # Aplica o threshold
                _, thresholded_img = cv2.threshold(img, threshold_value, 255, cv2.THRESH_BINARY)

                # Calcula a porcentagem de pixels pretos na imagem thresholded
                print(img)
                dark_percentage = calculate_dark_percentage(thresholded_img)

                # Verifica se a porcentagem de pixels pretos é maior ou igual ao corte definido
                if dark_percentage <= cut_off_percentage:
                    classification = 'Darkness'
                else:
#                     if std_deviation <= threshold_std:
#                         classification = 'Bad Lighting'
#                     else:
                    classification = 'Good Lighting'

                # Salva a imagem thresholded na pasta de saída para imagens
                output_img_path = os.path.join(output_folder, filename)
                cv2.imwrite(output_img_path, thresholded_img)

                # Escreve a classificação no arquivo de saída para texto
#                 file.write(f"{filename}: {dark_percentage:.2f}% {print_std:.2f} {classification}\n")
                file.write(f"{filename}: {dark_percentage:.2f}% {classification}\n")

#                 print(f"{filename}: {dark_percentage:.2f}% {print_std:.2f} {classification}")
                print(f"{filename}: {dark_percentage:.2f}% {classification}")

                new_row = {'root': root, 'filename': filename,'lighting':dark_percentage, 'classification': classification}

                # Convert dictionary to DataFrame with specified index
                new_row_df = pd.DataFrame([new_row], index=[0])

                # Concatenate DataFrame with df_output
                df_output = pd.concat([df_output, new_row_df], ignore_index=True)
                                
                

In [5]:
# # Pasta de entrada, pasta de saída para imagens e arquivo de saída para texto
# input_folder = "M70"
# output_image_folder = "threshold"
# output_text_file = "classificacoes.txt"
# threshold_value = 15
# cut_off_percentage = 85
# # threshold_std_mean = 0.7

# Aplica o threshold em todas as imagens na pasta de entrada e salva as imagens e as classificações em pastas/arquivos separados
# apply_threshold_to_images(input_folder, output_image_folder, output_text_file, threshold_value, threshold_std_mean, cut_off_percentage)
# apply_threshold_to_images(input_folder, output_image_folder, output_text_file, threshold_value, cut_off_percentage)

In [6]:
# Pasta de entrada, pasta de saída para imagens e arquivo de saída para texto
input_folder = r"C:\Users\Operacao\Downloads\Projeto C"
output_image_folder = r"C:\Users\Operacao\Downloads\imagens escuras"
output_text_file = "classificacoes.txt"
threshold_value = 15
cut_off_percentage = 85

df_output = pd.DataFrame({'root':[],'filename':[],'lighting':[],'classification':[]})

for root, dirs, files in os.walk(input_folder):
    apply_threshold_to_images(root, output_image_folder, output_text_file, threshold_value, cut_off_percentage)


df_output.to_excel('C:\\Users\\Operacao\\Downloads\\imagens escuras\\lista de imagens escuras mv31 PROJETO C.xlsx',index=False)

[[195 195 195 ... 195 195 195]
 [195 195 195 ... 195 195 195]
 [195 195 195 ... 195 195 195]
 ...
 [223 223 223 ... 223 223 223]
 [223 223 223 ... 223 223 223]
 [223 223 223 ... 223 223 223]]
IMG_20240319_192601_00_819.jpg: 93.67% Good Lighting
[[170 170 170 ... 170 170 170]
 [170 170 170 ... 170 170 170]
 [169 169 169 ... 170 170 170]
 ...
 [ 37  37  37 ...  37  37  37]
 [ 38  38  38 ...  38  38  38]
 [ 36  36  36 ...  36  36  36]]
IMG_20240319_192608_00_820.jpg: 90.23% Good Lighting
[[169 169 169 ... 169 169 169]
 [169 169 169 ... 169 169 169]
 [168 168 168 ... 168 168 168]
 ...
 [ 36  36  36 ...  36  36  36]
 [ 36  36  36 ...  36  36  36]
 [ 38  38  38 ...  38  38  38]]
IMG_20240319_192617_00_821.jpg: 90.72% Good Lighting
[[163 163 163 ... 164 164 164]
 [163 163 163 ... 164 164 164]
 [163 163 163 ... 164 164 164]
 ...
 [ 46  46  46 ...  46  46  46]
 [ 46  46  46 ...  46  46  46]
 [ 46  46  46 ...  46  46  46]]
IMG_20240319_192623_00_822.jpg: 89.92% Good Lighting
[[160 160 160 ... 16

error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:786: error: (-215:Assertion failed) !_img.empty() in function 'cv::imwrite'
